name: Build and deploy to Heroku

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build-push-release:
    runs-on: ubuntu-latest
    environment: heroku
    env:
      HEROKU_EMAIL: ${{ secrets.HEROKU_USER }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: react-app-bootstrap
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/react-app-bootstrap/web
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Heroku container registry
        run: echo ${HEROKU_API_KEY} | docker login -u ${HEROKU_EMAIL} registry.heroku.com --password-stdin
      - name: Pull previous image
        run: docker pull ${HEROKU_REGISTRY_IMAGE} || true
      - name: Build the container
        run: >
          docker build
          --target production
          --cache-from ${HEROKU_REGISTRY_IMAGE}
          --tag ${HEROKU_REGISTRY_IMAGE}
          -f Dockerfile.production "."
      - name: Push fresh image to Heroku container registry
        run: docker push $HEROKU_REGISTRY_IMAGE
      - name: Release on Heroku
        run: heroku container:release web --app ${HEROKU_APP_NAME}
